// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCntBZb01SWCtE25yPAEyjgld51m77od5w',
    appId: '1:489751560548:web:6b3572eceab17d955cfa71',
    messagingSenderId: '489751560548',
    projectId: 'jobhunt-dev-7b0ae',
    authDomain: 'jobhunt-dev-7b0ae.firebaseapp.com',
    storageBucket: 'jobhunt-dev-7b0ae.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCntBZb01SWCtE25yPAEyjgld51m77od5w',
    appId: '1:489751560548:android:6b3572eceab17d955cfa71',
    messagingSenderId: '489751560548',
    projectId: 'jobhunt-dev-7b0ae',
    storageBucket: 'jobhunt-dev-7b0ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCntBZb01SWCtE25yPAEyjgld51m77od5w',
    appId: '1:489751560548:ios:6b3572eceab17d955cfa71',
    messagingSenderId: '489751560548',
    projectId: 'jobhunt-dev-7b0ae',
    storageBucket: 'jobhunt-dev-7b0ae.firebasestorage.app',
    iosBundleId: 'com.jobhunt.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCntBZb01SWCtE25yPAEyjgld51m77od5w',
    appId: '1:489751560548:ios:6b3572eceab17d955cfa71',
    messagingSenderId: '489751560548',
    projectId: 'jobhunt-dev-7b0ae',
    storageBucket: 'jobhunt-dev-7b0ae.firebasestorage.app',
    iosBundleId: 'com.jobhunt.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCntBZb01SWCtE25yPAEyjgld51m77od5w',
    appId: '1:489751560548:web:6b3572eceab17d955cfa71',
    messagingSenderId: '489751560548',
    projectId: 'jobhunt-dev-7b0ae',
    authDomain: 'jobhunt-dev-7b0ae.firebaseapp.com',
    storageBucket: 'jobhunt-dev-7b0ae.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );
}
